### ISSUE TITLE
failed log report

### ISSUE THREAD

**Issue by aguygarner** [WGLab/NanoCaller#16]
I am sometimes getting a failed report for some of my scaffolds in some of my individuals. Not sure what is going on here; 

021-09-08 13:45:38.945625: SNP calling completed for contig contig_109746. Time taken= 10.9951

2021-09-08 13:45:38.945724: ------WhatsHap SNP phasing log------

This is WhatsHap 1.0 running under Python 3.6.13
Working on 1 samples from 1 family
======== Working on chromosome 'contig_109746'
---- Processing individual SAMPLE
Using maximum coverage per sample of 15X
Number of variants skipped due to missing genotypes: 0
Number of remaining heterozygous variants: 3
Reading alignments and detecting alleles ...
Found 43 reads covering 3 variants
Kept 34 reads that cover at least two variants each
Reducing coverage to at most 15X by selecting most informative reads ...
Selected 15 reads covering 3 variants
Best-case phasing would result in 1 non-singleton phased blocks (1 in total)
... after read selection: 1 non-singleton phased blocks (1 in total)
Variants covered by at least one phase-informative read in at least one individual after read selection: 3
Phasing 1 sample by solving the MEC problem ...
MEC cost: 150
No. of phased blocks: 1
Largest component contains 3 variants (100.0% of accessible variants) between position 8310 and 9657
======== Writing VCF
Done writing VCF

== SUMMARY ==
Maximum memory usage: 0.203 GB
Time spent reading BAM/CRAM:                    0.0 s
Time spent parsing VCF:                         0.0 s
Time spent selecting reads:                     0.0 s
Time spent phasing:                             0.0 s
Time spent writing VCF:                         0.0 s
Time spent finding components:                  0.0 s
Time spent on rest:                             0.3 s
Total elapsed time:                             0.4 s

2021-09-08 13:45:45.886753: ------SNP phasing completed------

2021-09-08 13:45:45.886864: ------WhatsHap BAM phasing log------

Found 1 samples in input VCF
Keeping 1 samples for haplo-tagging
Found 0 samples in BAM file
Reading alignments and detecting alleles ...
Found 43 reads covering 3 variants

== SUMMARY ==
Total alignments processed:                       189
Alignments that could be tagged:                   72
Alignments spanning multiple phase sets:            0
haplotag - total processing time: 0.5968549251556396

2021-09-08 13:45:50.542123: ------BAM phasing completed-----

2021-09-08 13:45:50.542413: Indel calling started.
Traceback (most recent call last):
  File "/n/home08/aggarner/NanoCaller/scripts/NanoCaller.py", line 257, in <module>
    run(args)
  File "/n/home08/aggarner/NanoCaller/scripts/NanoCaller.py", line 115, in run
    indel_vcf=indelCaller.test_model(in_dict, pool)
  File "/n/home08/aggarner/NanoCaller/scripts/indelCaller.py", line 106, in test_model
    for res in result:            
  File "/n/home08/aggarner/NanoCaller/scripts/generate_indel_pileups.py", line 328, in get_indel_testing_candidates
    ref=''.join([ref_dict[p] for p in range(v_pos-window_before,v_pos+window_after+1)])
  File "/n/home08/aggarner/NanoCaller/scripts/generate_indel_pileups.py", line 328, in <listcomp>
    ref=''.join([ref_dict[p] for p in range(v_pos-window_before,v_pos+window_after+1)])
KeyError: 10410

**Comment by umahsn** [comment]
Hi, thanks for pointing this out. The problem was with indels occurring near the end of contigs and I have updated the code to fix this issue. Please let me know if the latest commit fixes this issue on your end as well.

**Comment by aguygarner** [comment]
This seems to have fixed the error on my end.
