### ISSUE TITLE
docker build fails due to missing NanoCaller_WGS file

### ISSUE THREAD

**Issue by sbassi** [WGLab/NanoCaller#30]
When I try to build the image, I get an error in this step:

```
COPY ./NanoCaller_WGS /opt/conda/envs/nanocaller_env/bin
```

Since the NanoCaller_WGS file is missing.

**Comment by umahsn** [comment]
Hi,

I have fixed the Dockerfile by removing the line. NanoCaller V3 does not use NanoCaller_WGS, so the updated dockerfile should work now.

**Comment by sbassi** [comment]
thank you for the fix
