### ISSUE TITLE
AD (allelic depth) field

### ISSUE THREAD

**Issue by jamesdalg** [WGLab/NanoCaller#38]
To the community:
I really think this is a fantastic tool, with incredible speed and great options for phasing.
Is there a way to get the AD field to populate with NanoCaller, much like Deepvariant and GATK's HaplotypeCaller? There are multiple downstream tools that require this information and I'm wondering if I can somehow coax NanoCaller into giving this information, it would be a much faster alternative than deepvariant (which has some stages of the code that don't parallelize well and take days).

**Comment by umahsn** [comment]
Hi, thank you for bringing this to attention. I will add this functionality into NanoCaller.

**Comment by umahsn** [comment]
I have added information for allelic depth, for overall as well as forward/reverse strands, in the format field for SNPs. I will extend the functionality to indels soon.

**Comment by jamesdalg** [comment]
If you can, sometime, please update the docker image sometime if it's not too much trouble. I've never been able to get it to work on the cluster without using the image.

**Comment by umahsn** [comment]
I have pushed a new image version 3.4.0 that has allelic depths.

**Comment by jamesdalg** [comment]
Thanks so very much!! This is a huge help.
